#ifndef BPF_XLAT_H
#define BPF_XLAT_H

#include "xlat.h"

#include <linux/bpf.h>

const t_xlat_data bpf_flags_data[] = {
	XLAT(BPF_MAP_CREATE),
	XLAT(BPF_MAP_LOOKUP_ELEM),
	XLAT(BPF_MAP_UPDATE_ELEM),
	XLAT(BPF_MAP_DELETE_ELEM),
	XLAT(BPF_MAP_GET_NEXT_KEY),
	XLAT(BPF_PROG_LOAD),
	XLAT(BPF_OBJ_PIN),
	XLAT(BPF_OBJ_GET),
	XLAT(BPF_PROG_ATTACH),
	XLAT(BPF_PROG_DETACH),
	XLAT(BPF_PROG_TEST_RUN),
	XLAT(BPF_PROG_RUN),
	XLAT(BPF_PROG_GET_NEXT_ID),
	XLAT(BPF_MAP_GET_NEXT_ID),
	XLAT(BPF_PROG_GET_FD_BY_ID),
	XLAT(BPF_MAP_GET_FD_BY_ID),
	XLAT(BPF_OBJ_GET_INFO_BY_FD),
	XLAT(BPF_PROG_QUERY),
	XLAT(BPF_RAW_TRACEPOINT_OPEN),
	XLAT(BPF_BTF_LOAD),
	XLAT(BPF_BTF_GET_FD_BY_ID),
	XLAT(BPF_TASK_FD_QUERY),
	XLAT(BPF_MAP_LOOKUP_AND_DELETE_ELEM),
	XLAT(BPF_MAP_FREEZE),
	XLAT(BPF_BTF_GET_NEXT_ID),
	XLAT(BPF_MAP_LOOKUP_BATCH),
	XLAT(BPF_MAP_LOOKUP_AND_DELETE_BATCH),
	XLAT(BPF_MAP_UPDATE_BATCH),
	XLAT(BPF_MAP_DELETE_BATCH),
	XLAT(BPF_LINK_CREATE),
	XLAT(BPF_LINK_UPDATE),
	XLAT(BPF_LINK_GET_FD_BY_ID),
	XLAT(BPF_LINK_GET_NEXT_ID),
	XLAT(BPF_ENABLE_STATS),
	XLAT(BPF_ITER_CREATE),
	XLAT(BPF_LINK_DETACH),
	XLAT(BPF_PROG_BIND_MAP),
	XLAT(BPF_TOKEN_CREATE),
	XLAT(BPF_PROG_STREAM_READ_BY_FD),
};
WXLAT(bpf_flags);

#endif /* BPF_XLAT_H */