#ifndef CAPABILITY_XLAT_H
#define CAPABILITY_XLAT_H

#include "xlat.h"

#include <linux/capability.h>

const t_xlat_data capability_version_data[] = {
	XLAT(_LINUX_CAPABILITY_VERSION_1),
	XLAT(_LINUX_CAPABILITY_VERSION_2),
	XLAT(_LINUX_CAPABILITY_VERSION_3),
};
WXLAT(capability_version);

const t_xlat_data capability_u32s_data[] = {
	XLAT(_LINUX_CAPABILITY_U32S_1),
	XLAT(_LINUX_CAPABILITY_U32S_2),
};
WXLAT(capability_u32s);

const t_xlat_data capslo_data[] = {
	XLAT_NAMED(CAP_TO_MASK(CAP_CHOWN), "CAP_CHOWN"),
	XLAT_NAMED(CAP_TO_MASK(CAP_DAC_OVERRIDE), "CAP_DAC_OVERRIDE"),
	XLAT_NAMED(CAP_TO_MASK(CAP_DAC_READ_SEARCH), "CAP_DAC_READ_SEARCH"),
	XLAT_NAMED(CAP_TO_MASK(CAP_FOWNER), "CAP_FOWNER"),
	XLAT_NAMED(CAP_TO_MASK(CAP_FSETID), "CAP_FSETID"),
	XLAT_NAMED(CAP_TO_MASK(CAP_KILL), "CAP_KILL"),
	XLAT_NAMED(CAP_TO_MASK(CAP_SETGID), "CAP_SETGID"),
	XLAT_NAMED(CAP_TO_MASK(CAP_SETUID), "CAP_SETUID"),
	XLAT_NAMED(CAP_TO_MASK(CAP_SETPCAP), "CAP_SETPCAP"),
	XLAT_NAMED(CAP_TO_MASK(CAP_LINUX_IMMUTABLE), "CAP_LINUX_IMMUTABLE"),
	XLAT_NAMED(CAP_TO_MASK(CAP_NET_BIND_SERVICE), "CAP_NET_BIND_SERVICE"),
	XLAT_NAMED(CAP_TO_MASK(CAP_NET_BROADCAST), "CAP_NET_BROADCAST"),
	XLAT_NAMED(CAP_TO_MASK(CAP_NET_ADMIN), "CAP_NET_ADMIN"),
	XLAT_NAMED(CAP_TO_MASK(CAP_NET_RAW), "CAP_NET_RAW"),
	XLAT_NAMED(CAP_TO_MASK(CAP_IPC_LOCK), "CAP_IPC_LOCK"),
	XLAT_NAMED(CAP_TO_MASK(CAP_IPC_OWNER), "CAP_IPC_OWNER"),
	XLAT_NAMED(CAP_TO_MASK(CAP_SYS_MODULE), "CAP_SYS_MODULE"),
	XLAT_NAMED(CAP_TO_MASK(CAP_SYS_RAWIO), "CAP_SYS_RAWIO"),
	XLAT_NAMED(CAP_TO_MASK(CAP_SYS_CHROOT), "CAP_SYS_CHROOT"),
	XLAT_NAMED(CAP_TO_MASK(CAP_SYS_PTRACE), "CAP_SYS_PTRACE"),
	XLAT_NAMED(CAP_TO_MASK(CAP_SYS_PACCT), "CAP_SYS_PACCT"),
	XLAT_NAMED(CAP_TO_MASK(CAP_SYS_ADMIN), "CAP_SYS_ADMIN"),
	XLAT_NAMED(CAP_TO_MASK(CAP_SYS_BOOT), "CAP_SYS_BOOT"),
	XLAT_NAMED(CAP_TO_MASK(CAP_SYS_NICE), "CAP_SYS_NICE"),
	XLAT_NAMED(CAP_TO_MASK(CAP_SYS_RESOURCE), "CAP_SYS_RESOURCE"),
	XLAT_NAMED(CAP_TO_MASK(CAP_SYS_TIME), "CAP_SYS_TIME"),
	XLAT_NAMED(CAP_TO_MASK(CAP_SYS_TTY_CONFIG), "CAP_SYS_TTY_CONFIG"),
	XLAT_NAMED(CAP_TO_MASK(CAP_MKNOD), "CAP_MKNOD"),
	XLAT_NAMED(CAP_TO_MASK(CAP_LEASE), "CAP_LEASE"),
	XLAT_NAMED(CAP_TO_MASK(CAP_AUDIT_WRITE), "CAP_AUDIT_WRITE"),
	XLAT_NAMED(CAP_TO_MASK(CAP_AUDIT_CONTROL), "CAP_AUDIT_CONTROL"),
	XLAT_NAMED(CAP_TO_MASK(CAP_SETFCAP), "CAP_SETFCAP"),
};
WXLAT(capslo);

const t_xlat_data capshi_data[] = {
	XLAT_NAMED(CAP_TO_MASK(CAP_MAC_OVERRIDE - 32), "CAP_MAC_OVERRIDE"),
	XLAT_NAMED(CAP_TO_MASK(CAP_MAC_ADMIN - 32), "CAP_MAC_ADMIN"),
	XLAT_NAMED(CAP_TO_MASK(CAP_SYSLOG - 32), "CAP_SYSLOG"),
	XLAT_NAMED(CAP_TO_MASK(CAP_WAKE_ALARM - 32), "CAP_WAKE_ALARM"),
	XLAT_NAMED(CAP_TO_MASK(CAP_BLOCK_SUSPEND - 32), "CAP_BLOCK_SUSPEND"),
	XLAT_NAMED(CAP_TO_MASK(CAP_AUDIT_READ - 32), "CAP_AUDIT_READ"),
	XLAT_NAMED(CAP_TO_MASK(CAP_PERFMON - 32), "CAP_PERFMON"),
	XLAT_NAMED(CAP_TO_MASK(CAP_BPF - 32), "CAP_BPF"),
	XLAT_NAMED(CAP_TO_MASK(CAP_CHECKPOINT_RESTORE - 32), "CAP_CHECKPOINT_RESTORE"),
};
WXLAT(capshi);

#endif /* CAPABILITY_XLAT_H */
