#ifndef EXEC_DOMAIN_XLAT_H
#define EXEC_DOMAIN_XLAT_H

#include "xlat.h"

#include <sys/personality.h>

const t_xlat_data persona_flags_data[] = {
	XLAT(UNAME26),
	XLAT(ADDR_NO_RANDOMIZE),
	XLAT(FDPIC_FUNCPTRS),
	XLAT(MMAP_PAGE_ZERO),
	XLAT(ADDR_COMPAT_LAYOUT),
	XLAT(READ_IMPLIES_EXEC),
	XLAT(ADDR_LIMIT_32BIT),
	XLAT(SHORT_INODE),
	XLAT(WHOLE_SECONDS),
	XLAT(STICKY_TIMEOUTS),
	XLAT(ADDR_LIMIT_3GB),
};
WXLAT(persona_flags);

const t_xlat_data persona_types_data[] = {
	XLAT(PER_LINUX),
	XLAT(PER_LINUX_32BIT),
	XLAT(PER_LINUX_FDPIC),
	XLAT(PER_SVR4),
	XLAT(PER_SVR3),
	XLAT(PER_SCOSVR3),
	XLAT(PER_OSR5),
	XLAT(PER_WYSEV386),
	XLAT(PER_ISCR4),
	XLAT(PER_BSD),
	XLAT(PER_SUNOS),
	XLAT(PER_XENIX),
	XLAT(PER_LINUX32),
	XLAT(PER_LINUX32_3GB),
	XLAT(PER_IRIX32),
	XLAT(PER_IRIXN32),
	XLAT(PER_IRIX64),
	XLAT(PER_RISCOS),
	XLAT(PER_SOLARIS),
	XLAT(PER_UW7),
	XLAT(PER_OSF4),
	XLAT(PER_HPUX),
	XLAT(PER_MASK),
};
WXLAT(persona_types);

#endif