#ifndef FANOTIFY_XLAT_H
#define FANOTIFY_XLAT_H

#include "xlat.h"

#include <linux/fanotify.h>

const t_xlat_data fan_class_flags_data[] = {
	XLAT(FAN_CLASS_NOTIF),
	XLAT(FAN_CLASS_CONTENT),
	XLAT(FAN_CLASS_PRE_CONTENT),
};
WXLAT(fan_class_flags);

const t_xlat_data fan_events_data[] = {
	XLAT(FAN_ACCESS),
	XLAT(FAN_MODIFY),
	XLAT(FAN_ATTRIB),
	XLAT(FAN_CLOSE),
	XLAT(FAN_CLOSE_WRITE),
	XLAT(FAN_CLOSE_NOWRITE),
	XLAT(FAN_OPEN),
	XLAT(FAN_MOVE),
	XLAT(FAN_MOVED_FROM),
	XLAT(FAN_MOVED_TO),
	XLAT(FAN_CREATE),
	XLAT(FAN_DELETE),
	XLAT(FAN_DELETE_SELF),
	XLAT(FAN_MOVE_SELF),
	XLAT(FAN_OPEN_EXEC),
	XLAT(FAN_Q_OVERFLOW),
	XLAT(FAN_FS_ERROR),
	XLAT(FAN_OPEN_PERM),
	XLAT(FAN_ACCESS_PERM),
	XLAT(FAN_OPEN_EXEC_PERM),
//	XLAT(FAN_PRE_ACCESS),
//	XLAT(FAN_MNT_ATTACH),
//	XLAT(FAN_MNT_DETACH),
//	XLAT(FAN_EVENT_ON_CHILD),
//	XLAT(FAN_RENAME),
//	XLAT(FAN_ONDIR),
};
WXLAT(fan_events);

const t_xlat_data fan_init_flags_data[] = {
	XLAT(FAN_CLOEXEC),
	XLAT(FAN_NONBLOCK),
	XLAT(FAN_UNLIMITED_QUEUE),
	XLAT(FAN_UNLIMITED_MARKS),
	XLAT(FAN_ENABLE_AUDIT),
	XLAT(FAN_REPORT_PIDFD),
	XLAT(FAN_REPORT_TID),
	XLAT(FAN_REPORT_FID),
	XLAT(FAN_REPORT_DIR_FID),
	XLAT(FAN_REPORT_NAME),
	XLAT(FAN_REPORT_TARGET_FID),
	XLAT(FAN_REPORT_FD_ERROR),
//	XLAT(FAN_REPORT_MNT),
};
WXLAT(fan_init_flags);

const t_xlat_data fan_mark_flags_data[] = {
	XLAT(FAN_MARK_ADD),
	XLAT(FAN_MARK_REMOVE),
	XLAT(FAN_MARK_DONT_FOLLOW),
	XLAT(FAN_MARK_ONLYDIR),
	XLAT(FAN_MARK_IGNORED_MASK),
	XLAT(FAN_MARK_IGNORED_SURV_MODIFY),
	XLAT(FAN_MARK_FLUSH),
	XLAT(FAN_MARK_EVICTABLE),
	XLAT(FAN_MARK_IGNORE),
	XLAT(FAN_MARK_INODE),
	XLAT(FAN_MARK_MOUNT),
	XLAT(FAN_MARK_FILESYSTEM),
//	XLAT(FAN_MARK_MNTNS),
};
WXLAT(fan_mark_flags);

#endif /* FANOTIFY_XLAT_H */
