#ifndef FCNTL_XLAT
#define FCNTL_XLAT

#include "xlat.h"

#include <linux/fcntl.h>

#ifndef F_GETLK64
#  define F_GETLK64  12
#  define F_SETLK64  13
#  define F_SETLKW64 14
#endif

const t_xlat_data fctnl_flags_data[] = {
	XLAT(F_DUPFD),
	XLAT(F_GETFD),
	XLAT(F_SETFD),
	XLAT(F_GETFL),
	XLAT(F_SETFL),
	XLAT(F_GETLK),
	XLAT(F_SETLK),
	XLAT(F_SETLKW),
	XLAT(F_SETOWN),
	XLAT(F_GETOWN),
	XLAT(F_SETSIG),
	XLAT(F_GETSIG),
	XLAT(F_GETLK64),
	XLAT(F_SETLK64),
	XLAT(F_SETLKW64),
	XLAT(F_SETOWN_EX),
	XLAT(F_GETOWN_EX),
	XLAT(F_GETOWNER_UIDS),
	XLAT(F_OFD_GETLK),
	XLAT(F_OFD_SETLK),
	XLAT(F_OFD_SETLKW),
	XLAT(F_SETLEASE),
	XLAT(F_GETLEASE),
	XLAT(F_NOTIFY),
//	XLAT(F_DUPFD_QUERY),
//	XLAT(F_CREATED_QUERY),
	XLAT(F_CANCELLK),
	XLAT(F_DUPFD_CLOEXEC),
	XLAT(F_SETPIPE_SZ),
	XLAT(F_GETPIPE_SZ),
	XLAT(F_ADD_SEALS),
	XLAT(F_GET_SEALS),
};

WXLAT(fctnl_flags);

#endif
