#ifndef FORK_XLAT_H
#define FORK_XLAT_H

#include "xlat.h"
#ifndef __USE_GNU
#  define UDF_USE_GNU
#  define __USE_GNU
#endif
#include <sched.h>
#ifdef UDF_USE_GNU
#  undef UDF_USE_GNU
#  undef __USE_GNU
#endif

const t_xlat_data clone_flags_data[] = {
	XLAT(CLONE_VM),
	XLAT(CLONE_FS),
	XLAT(CLONE_FILES),
	XLAT(CLONE_SIGHAND),
	XLAT(CLONE_PIDFD),
	XLAT(CLONE_PTRACE),
	XLAT(CLONE_VFORK),
	XLAT(CLONE_PARENT),
	XLAT(CLONE_THREAD),
	XLAT(CLONE_NEWNS),
	XLAT(CLONE_SYSVSEM),
	XLAT(CLONE_SETTLS),
	XLAT(CLONE_PARENT_SETTID),
	XLAT(CLONE_CHILD_CLEARTID),
	XLAT(CLONE_DETACHED),
	XLAT(CLONE_UNTRACED),
	XLAT(CLONE_CHILD_SETTID),
	XLAT(CLONE_NEWCGROUP),
	XLAT(CLONE_NEWUTS),
	XLAT(CLONE_NEWIPC),
	XLAT(CLONE_NEWUSER),
	XLAT(CLONE_NEWPID),
	XLAT(CLONE_NEWNET),
	XLAT(CLONE_IO),
	XLAT(CLONE_NEWTIME),
};
WXLAT(clone_flags);

#endif