#ifndef FUTEX_XLAT_H
#define FUTEX_XLAT_H

#include "xlat.h"

#include <linux/futex.h>

const t_xlat_data futex_ops_data[] = {
	XLAT(FUTEX_WAIT),
	XLAT(FUTEX_WAKE),
	XLAT(FUTEX_FD),
	XLAT(FUTEX_REQUEUE),
	XLAT(FUTEX_CMP_REQUEUE),
	XLAT(FUTEX_WAKE_OP),
	XLAT(FUTEX_LOCK_PI),
	XLAT(FUTEX_UNLOCK_PI),
	XLAT(FUTEX_TRYLOCK_PI),
	XLAT(FUTEX_WAIT_BITSET),
	XLAT(FUTEX_WAKE_BITSET),
	XLAT(FUTEX_WAIT_REQUEUE_PI),
	XLAT(FUTEX_CMP_REQUEUE_PI),
	XLAT(FUTEX_LOCK_PI2),
	XLAT(FUTEX_WAIT_PRIVATE),
	XLAT(FUTEX_WAKE_PRIVATE),
	XLAT(FUTEX_REQUEUE_PRIVATE),
	XLAT(FUTEX_CMP_REQUEUE_PRIVATE),
	XLAT(FUTEX_WAKE_OP_PRIVATE),
	XLAT(FUTEX_LOCK_PI_PRIVATE),
	XLAT(FUTEX_LOCK_PI2_PRIVATE),
	XLAT(FUTEX_UNLOCK_PI_PRIVATE),
	XLAT(FUTEX_TRYLOCK_PI_PRIVATE),
	XLAT(FUTEX_WAIT_BITSET_PRIVATE),
	XLAT(FUTEX_WAKE_BITSET_PRIVATE),
	XLAT(FUTEX_WAIT_REQUEUE_PI_PRIVATE),
	XLAT(FUTEX_CMP_REQUEUE_PI_PRIVATE),
};
WXLAT(futex_ops);

const t_xlat_data futex_bitsets_data[] = {
	XLAT(FUTEX_BITSET_MATCH_ANY),
};
WXLAT(futex_bitsets);

const t_xlat_data futex2_size_flags_data[] = {
	XLAT(FUTEX2_SIZE_U8),
	XLAT(FUTEX2_SIZE_U16),
	XLAT(FUTEX2_SIZE_U32),
	XLAT(FUTEX2_SIZE_U64),
};
WXLAT(futex2_size_flags);

#ifndef FUTEX2_MPOL
#  define FUTEX2_MPOL 0x08
#endif
const t_xlat_data futex2_flags_data[] = {
	XLAT(FUTEX2_NUMA),
	XLAT(FUTEX2_MPOL),
	XLAT(FUTEX2_PRIVATE),
};
WXLAT(futex2_flags);

const t_xlat_data futex2_bitset_data[] = {
	XLAT(FUTEX_BITSET_MATCH_ANY),
};
WXLAT(futex2_bitset);

#endif /* FUTEX_XLAT_H */
