#ifndef IO_URING_XLAT_H
#define IO_URING_XLAT_H

#include "xlat.h"

#include <linux/io_uring.h>

const t_xlat_data ioring_enter_flags_data[] = {
	XLAT(IORING_ENTER_GETEVENTS),
	XLAT(IORING_ENTER_SQ_WAKEUP),
	XLAT(IORING_ENTER_SQ_WAIT),
	XLAT(IORING_ENTER_EXT_ARG),
	XLAT(IORING_ENTER_REGISTERED_RING),
//	XLAT(IORING_ENTER_ABS_TIMER),
//	XLAT(IORING_ENTER_EXT_ARG_REG),
//	XLAT(IORING_ENTER_NO_IOWAIT),
};
WXLAT(ioring_enter_flags);

const t_xlat_data ioring_register_flags_data[] = {
	XLAT(IORING_REGISTER_BUFFERS),
	XLAT(IORING_UNREGISTER_BUFFERS),
	XLAT(IORING_REGISTER_FILES),
	XLAT(IORING_UNREGISTER_FILES),
	XLAT(IORING_REGISTER_EVENTFD),
	XLAT(IORING_UNREGISTER_EVENTFD),
	XLAT(IORING_REGISTER_FILES_UPDATE),
	XLAT(IORING_REGISTER_EVENTFD_ASYNC),
	XLAT(IORING_REGISTER_PROBE),
	XLAT(IORING_REGISTER_PERSONALITY),
	XLAT(IORING_UNREGISTER_PERSONALITY),
	XLAT(IORING_REGISTER_RESTRICTIONS),
	XLAT(IORING_REGISTER_ENABLE_RINGS),
	XLAT(IORING_REGISTER_FILES2),
	XLAT(IORING_REGISTER_FILES_UPDATE2),
	XLAT(IORING_REGISTER_BUFFERS2),
	XLAT(IORING_REGISTER_BUFFERS_UPDATE),
	XLAT(IORING_REGISTER_IOWQ_AFF),
	XLAT(IORING_UNREGISTER_IOWQ_AFF),
	XLAT(IORING_REGISTER_IOWQ_MAX_WORKERS),
	XLAT(IORING_REGISTER_RING_FDS),
	XLAT(IORING_UNREGISTER_RING_FDS),
	XLAT(IORING_REGISTER_PBUF_RING),
	XLAT(IORING_UNREGISTER_PBUF_RING),
	XLAT(IORING_REGISTER_SYNC_CANCEL),
	XLAT(IORING_REGISTER_FILE_ALLOC_RANGE),
	XLAT(IORING_REGISTER_PBUF_STATUS),
//	XLAT(IORING_REGISTER_NAPI),
//	XLAT(IORING_UNREGISTER_NAPI),
//	XLAT(IORING_REGISTER_CLOCK),
//	XLAT(IORING_REGISTER_CLONE_BUFFERS),
//	XLAT(IORING_REGISTER_SEND_MSG_RING),
//	XLAT(IORING_REGISTER_ZCRX_IFQ),
//	XLAT(IORING_REGISTER_RESIZE_RINGS),
//	XLAT(IORING_REGISTER_MEM_REGION),
//	XLAT(IORING_REGISTER_QUERY),
//	XLAT(IORING_REGISTER_ZCRX_CTRL),
};
WXLAT(ioring_register_flags);

#endif /* IO_URING_XLAT_H */
