#ifndef KEXEC_XLAT_H
#define KEXEC_XLAT_H

#include "xlat.h"

#include <linux/kexec.h>

const t_xlat_data kexec_flags_data[] = {
	XLAT(KEXEC_ON_CRASH),
	XLAT(KEXEC_PRESERVE_CONTEXT),
	XLAT(KEXEC_UPDATE_ELFCOREHDR),
	XLAT(KEXEC_CRASH_HOTPLUG_SUPPORT),
};
WXLAT(kexec_flags);

const t_xlat_data kexec_archs_data[] = {
	XLAT(KEXEC_ARCH_DEFAULT),
	XLAT(KEXEC_ARCH_386),
	XLAT(KEXEC_ARCH_68K),
	XLAT(KEXEC_ARCH_PARISC),
	XLAT(KEXEC_ARCH_X86_64),
	XLAT(KEXEC_ARCH_PPC),
	XLAT(KEXEC_ARCH_PPC64),
	XLAT(KEXEC_ARCH_IA_64),
	XLAT(KEXEC_ARCH_ARM),
	XLAT(KEXEC_ARCH_S390),
	XLAT(KEXEC_ARCH_SH),
	XLAT(KEXEC_ARCH_MIPS_LE),
	XLAT(KEXEC_ARCH_MIPS),
	XLAT(KEXEC_ARCH_AARCH64),
	XLAT(KEXEC_ARCH_RISCV),
	XLAT(KEXEC_ARCH_LOONGARCH),
};
WXLAT(kexec_archs);

const t_xlat_data kexec_file_load_flags_data[] = {
	XLAT(KEXEC_FILE_UNLOAD),
	XLAT(KEXEC_FILE_ON_CRASH),
	XLAT(KEXEC_FILE_NO_INITRAMFS),
	XLAT(KEXEC_FILE_DEBUG),
	XLAT(KEXEC_FILE_NO_CMA),
	XLAT(KEXEC_FILE_FORCE_DTB),
};
WXLAT(kexec_file_load_flags);

#endif /* KEXEC_XLAT_H */