#ifndef KEYCTL_XLAT_H
#define KEYCTL_XLAT_H

#include "xlat.h"

#include <linux/keyctl.h>

const t_xlat_data key_spec_ids_data[] = {
	XLAT(KEY_SPEC_THREAD_KEYRING),
	XLAT(KEY_SPEC_PROCESS_KEYRING),
	XLAT(KEY_SPEC_SESSION_KEYRING),
	XLAT(KEY_SPEC_USER_KEYRING),
	XLAT(KEY_SPEC_USER_SESSION_KEYRING),
	XLAT(KEY_SPEC_GROUP_KEYRING),
	XLAT(KEY_SPEC_REQKEY_AUTH_KEY),
	XLAT(KEY_SPEC_REQUESTOR_KEYRING),
};
WXLAT(key_spec_ids);

const char *keyctl_cmds[] = {
	XLAT_INDEXED(KEYCTL_GET_KEYRING_ID),
	XLAT_INDEXED(KEYCTL_JOIN_SESSION_KEYRING),
	XLAT_INDEXED(KEYCTL_UPDATE),
	XLAT_INDEXED(KEYCTL_REVOKE),
	XLAT_INDEXED(KEYCTL_CHOWN),
	XLAT_INDEXED(KEYCTL_SETPERM),
	XLAT_INDEXED(KEYCTL_DESCRIBE),
	XLAT_INDEXED(KEYCTL_CLEAR),
	XLAT_INDEXED(KEYCTL_LINK),
	XLAT_INDEXED(KEYCTL_UNLINK),
	XLAT_INDEXED(KEYCTL_SEARCH),
	XLAT_INDEXED(KEYCTL_READ),
	XLAT_INDEXED(KEYCTL_INSTANTIATE),
	XLAT_INDEXED(KEYCTL_NEGATE),
	XLAT_INDEXED(KEYCTL_SET_REQKEY_KEYRING),
	XLAT_INDEXED(KEYCTL_SET_TIMEOUT),
	XLAT_INDEXED(KEYCTL_ASSUME_AUTHORITY),
	XLAT_INDEXED(KEYCTL_GET_SECURITY),
	XLAT_INDEXED(KEYCTL_SESSION_TO_PARENT),
	XLAT_INDEXED(KEYCTL_REJECT),
	XLAT_INDEXED(KEYCTL_INSTANTIATE_IOV),
	XLAT_INDEXED(KEYCTL_INVALIDATE),
	XLAT_INDEXED(KEYCTL_GET_PERSISTENT),
	XLAT_INDEXED(KEYCTL_DH_COMPUTE),
	XLAT_INDEXED(KEYCTL_PKEY_QUERY),
	XLAT_INDEXED(KEYCTL_PKEY_ENCRYPT),
	XLAT_INDEXED(KEYCTL_PKEY_DECRYPT),
	XLAT_INDEXED(KEYCTL_PKEY_SIGN),
	XLAT_INDEXED(KEYCTL_PKEY_VERIFY),
	XLAT_INDEXED(KEYCTL_RESTRICT_KEYRING),
	XLAT_INDEXED(KEYCTL_MOVE),
	XLAT_INDEXED(KEYCTL_CAPABILITIES),
	XLAT_INDEXED(KEYCTL_WATCH_KEY),
};

#endif /* KEYCTL_XLAT_H */