#ifndef MEM_XLAT_H
#define MEM_XLAT_H

#include "xlat.h"
#include <linux/mman.h>

const t_xlat_data mmap_prots_data[] = {
	XLAT(PROT_EXEC),
	XLAT(PROT_READ),
	XLAT(PROT_WRITE),
	XLAT(PROT_NONE),
};
WXLAT(mmap_prots);

const t_xlat_data mmap_map_types_data[] = {
	XLAT(MAP_SHARED),
	XLAT(MAP_SHARED_VALIDATE),
	XLAT(MAP_PRIVATE),
	XLAT(MAP_DROPPABLE),
};
WXLAT(mmap_map_types);

const t_xlat_data mmap_flags_data[] = {
	XLAT(MAP_FILE),
	XLAT(MAP_FIXED),
	XLAT(MAP_ANONYMOUS),
	XLAT(MAP_32BIT),
	XLAT(MAP_ABOVE4G),
	XLAT(MAP_GROWSDOWN),
	XLAT(MAP_DENYWRITE),
	XLAT(MAP_EXECUTABLE),
	XLAT(MAP_LOCKED),
	XLAT(MAP_NORESERVE),
	XLAT(MAP_POPULATE),
	XLAT(MAP_NONBLOCK),
	XLAT(MAP_STACK),
	XLAT(MAP_HUGETLB),
#ifdef MAP_SYNC
	XLAT(MAP_SYNC),
#endif
#ifdef MAP_FIXED_NOREPLACE
	XLAT(MAP_FIXED_NOREPLACE),
#endif
};
WXLAT(mmap_flags);

const t_xlat_data mprotect_prots_data[] = {
	XLAT(PROT_EXEC),
	XLAT(PROT_READ),
	XLAT(PROT_WRITE),
	XLAT(PROT_NONE),
	XLAT(PROT_GROWSUP),
	XLAT(PROT_GROWSDOWN),
};
WXLAT(mprotect_prots);

const t_xlat_data mremap_flags_data[] = {
	XLAT(MREMAP_MAYMOVE),
	XLAT(MREMAP_FIXED),
	XLAT(MREMAP_DONTUNMAP),
};
WXLAT(mremap_flags);

const t_xlat_data msync_flags_data[] = {
	XLAT(MS_ASYNC),
	XLAT(MS_INVALIDATE),
	XLAT(MS_SYNC),
};
WXLAT(msync_flags);

const t_xlat_data madvise_values_data[] = {
	XLAT(MADV_NORMAL),
	XLAT(MADV_RANDOM),
	XLAT(MADV_SEQUENTIAL),
	XLAT(MADV_WILLNEED),
	XLAT(MADV_DONTNEED),
	XLAT(MADV_FREE),
	XLAT(MADV_REMOVE),
	XLAT(MADV_DONTFORK),
	XLAT(MADV_DOFORK),
	XLAT(MADV_HWPOISON),
	XLAT(MADV_SOFT_OFFLINE),
	XLAT(MADV_MERGEABLE),
	XLAT(MADV_UNMERGEABLE),
	XLAT(MADV_HUGEPAGE),
	XLAT(MADV_NOHUGEPAGE),
	XLAT(MADV_DONTDUMP),
	XLAT(MADV_DODUMP),
	XLAT(MADV_WIPEONFORK),
	XLAT(MADV_KEEPONFORK),
	XLAT(MADV_COLD),
	XLAT(MADV_PAGEOUT),
	XLAT(MADV_POPULATE_READ),
	XLAT(MADV_POPULATE_WRITE),
	XLAT(MADV_DONTNEED_LOCKED),
	XLAT(MADV_COLLAPSE),
	XLAT(MADV_GUARD_INSTALL),
	XLAT(MADV_GUARD_REMOVE),
};
WXLAT(madvise_values);

#endif