#ifndef NAMESPACE_XLAT_H
#define NAMESPACE_XLAT_H

#include "xlat.h"

#include <linux/fcntl.h>
#include <sys/mount.h>

const t_xlat_data mount_flags_data[] = {
	XLAT(MS_RDONLY),
	XLAT(MS_NOSUID),
	XLAT(MS_NODEV),
	XLAT(MS_NOEXEC),
	XLAT(MS_SYNCHRONOUS),
	XLAT(MS_REMOUNT),
	XLAT(MS_MANDLOCK),
	XLAT(MS_DIRSYNC),
	XLAT(MS_NOSYMFOLLOW),
	XLAT(MS_NOATIME),
	XLAT(MS_NODIRATIME),
	XLAT(MS_BIND),
	XLAT(MS_MOVE),
	XLAT(MS_REC),
	XLAT(MS_SILENT),
	XLAT(MS_POSIXACL),
	XLAT(MS_UNBINDABLE),
	XLAT(MS_PRIVATE),
	XLAT(MS_SLAVE),
	XLAT(MS_SHARED),
	XLAT(MS_RELATIME),
	XLAT(MS_KERNMOUNT),
	XLAT(MS_I_VERSION),
	XLAT(MS_STRICTATIME),
	XLAT(MS_LAZYTIME),
	XLAT(MS_ACTIVE),
	XLAT(MS_NOUSER),
};
WXLAT(mount_flags);

const t_xlat_data umount_flags_data[] = {
	XLAT(MNT_FORCE),
	XLAT(MNT_DETACH),
	XLAT(MNT_EXPIRE),
	XLAT(UMOUNT_NOFOLLOW),
};
WXLAT(umount_flags);

const t_xlat_data open_tree_flags_data[] = {
	XLAT(OPEN_TREE_CLONE),
	XLAT(OPEN_TREE_CLOEXEC),
	XLAT(AT_SYMLINK_NOFOLLOW),
	XLAT(AT_NO_AUTOMOUNT),
	XLAT(AT_EMPTY_PATH),
	XLAT(AT_RECURSIVE),
};
WXLAT(open_tree_flags);

const t_xlat_data mount_setattr_flags_data[] = {
	XLAT(AT_SYMLINK_NOFOLLOW),
	XLAT(AT_NO_AUTOMOUNT),
	XLAT(AT_EMPTY_PATH),
	XLAT(AT_RECURSIVE),
};
WXLAT(mount_setattr_flags);

const t_xlat_data move_mount_flags_data[] = {
	XLAT(MOVE_MOUNT_F_SYMLINKS),
	XLAT(MOVE_MOUNT_F_AUTOMOUNTS),
	XLAT(MOVE_MOUNT_F_EMPTY_PATH),
	XLAT(MOVE_MOUNT_T_SYMLINKS),
	XLAT(MOVE_MOUNT_T_AUTOMOUNTS),
	XLAT(MOVE_MOUNT_T_EMPTY_PATH),
	XLAT(MOVE_MOUNT_SET_GROUP),
	XLAT(MOVE_MOUNT_BENEATH),
};
WXLAT(move_mount_flags);

const t_xlat_data mount_attr_attributes_data[] = {
	XLAT(MOUNT_ATTR_RDONLY),
	XLAT(MOUNT_ATTR_NOSUID),
	XLAT(MOUNT_ATTR_NODEV),
	XLAT(MOUNT_ATTR_NOEXEC),
	XLAT(MOUNT_ATTR__ATIME),
	XLAT(MOUNT_ATTR_RELATIME),
	XLAT(MOUNT_ATTR_NOATIME),
	XLAT(MOUNT_ATTR_STRICTATIME),
	XLAT(MOUNT_ATTR_NODIRATIME),
	XLAT(MOUNT_ATTR_IDMAP),
	XLAT(MOUNT_ATTR_NOSYMFOLLOW),
};
WXLAT(mount_attr_attributes);

const t_xlat_data mount_attr_propagation_types_data[] = {
	XLAT(MS_UNBINDABLE),
	XLAT(MS_PRIVATE),
	XLAT(MS_SLAVE),
	XLAT(MS_SHARED),
};
WXLAT(mount_attr_propagation_types);

#endif /* NAMESPACE_XLAT_H */