#ifndef NAMESPACE_XLAT_H
#define NAMESPACE_XLAT_H

#include "xlat.h"

#include <sys/mount.h>

const t_xlat_data mount_flags_data[] = {
	XLAT(MS_RDONLY),
	XLAT(MS_NOSUID),
	XLAT(MS_NODEV),
	XLAT(MS_NOEXEC),
	XLAT(MS_SYNCHRONOUS),
	XLAT(MS_REMOUNT),
	XLAT(MS_MANDLOCK),
	XLAT(MS_DIRSYNC),
	XLAT(MS_NOSYMFOLLOW),
	XLAT(MS_NOATIME),
	XLAT(MS_NODIRATIME),
	XLAT(MS_BIND),
	XLAT(MS_MOVE),
	XLAT(MS_REC),
	XLAT(MS_SILENT),
	XLAT(MS_POSIXACL),
	XLAT(MS_UNBINDABLE),
	XLAT(MS_PRIVATE),
	XLAT(MS_SLAVE),
	XLAT(MS_SHARED),
	XLAT(MS_RELATIME),
	XLAT(MS_KERNMOUNT),
	XLAT(MS_I_VERSION),
	XLAT(MS_STRICTATIME),
	XLAT(MS_LAZYTIME),
	XLAT(MS_ACTIVE),
	XLAT(MS_NOUSER),
};
WXLAT(mount_flags);

const t_xlat_data umount_flags_data[] = {
	XLAT(MNT_FORCE),
	XLAT(MNT_DETACH),
	XLAT(MNT_EXPIRE),
	XLAT(UMOUNT_NOFOLLOW),
};
WXLAT(umount_flags);

#endif /* NAMESPACE_XLAT_H */