#ifndef PRINTK_XLAT_H
#define PRINTK_XLAT_H

#include "xlat.h"

#include <sys/klog.h>

#ifndef SYSLOG_ACTION_CLOSE
#  define SYSLOG_ACTION_CLOSE 0
#endif
#ifndef SYSLOG_ACTION_OPEN
#  define SYSLOG_ACTION_OPEN 1
#endif
#ifndef SYSLOG_ACTION_READ
#  define SYSLOG_ACTION_READ 2
#endif
#ifndef SYSLOG_ACTION_READ_ALL
#  define SYSLOG_ACTION_READ_ALL 3
#endif
#ifndef SYSLOG_ACTION_READ_CLEAR
#  define SYSLOG_ACTION_READ_CLEAR 4
#endif
#ifndef SYSLOG_ACTION_CLEAR
#  define SYSLOG_ACTION_CLEAR 5
#endif
#ifndef SYSLOG_ACTION_CONSOLE_OFF
#  define SYSLOG_ACTION_CONSOLE_OFF 6
#endif
#ifndef SYSLOG_ACTION_CONSOLE_ON
#  define SYSLOG_ACTION_CONSOLE_ON 7
#endif
#ifndef SYSLOG_ACTION_CONSOLE_LEVEL
#  define SYSLOG_ACTION_CONSOLE_LEVEL 8
#endif
#ifndef SYSLOG_ACTION_SIZE_UNREAD
#  define SYSLOG_ACTION_SIZE_UNREAD 9
#endif
#ifndef SYSLOG_ACTION_SIZE_BUFFER
#  define SYSLOG_ACTION_SIZE_BUFFER 10
#endif

const char *syslog_actions[] = {
	XLAT_INDEXED(SYSLOG_ACTION_CLOSE),
	XLAT_INDEXED(SYSLOG_ACTION_OPEN),
	XLAT_INDEXED(SYSLOG_ACTION_READ),
	XLAT_INDEXED(SYSLOG_ACTION_READ_ALL),
	XLAT_INDEXED(SYSLOG_ACTION_READ_CLEAR),
	XLAT_INDEXED(SYSLOG_ACTION_CLEAR),
	XLAT_INDEXED(SYSLOG_ACTION_CONSOLE_OFF),
	XLAT_INDEXED(SYSLOG_ACTION_CONSOLE_ON),
	XLAT_INDEXED(SYSLOG_ACTION_CONSOLE_LEVEL),
	XLAT_INDEXED(SYSLOG_ACTION_SIZE_UNREAD),
	XLAT_INDEXED(SYSLOG_ACTION_SIZE_BUFFER),
};

#ifndef LOGLEVEL_EMERG
#  define LOGLEVEL_EMERG 0
#endif
#ifndef LOGLEVEL_ALERT
#  define LOGLEVEL_ALERT 1
#endif
#ifndef LOGLEVEL_CRIT
#  define LOGLEVEL_CRIT 2
#endif
#ifndef LOGLEVEL_ERR
#  define LOGLEVEL_ERR 3
#endif
#ifndef LOGLEVEL_WARNING
#  define LOGLEVEL_WARNING 4
#endif
#ifndef LOGLEVEL_NOTICE
#  define LOGLEVEL_NOTICE 5
#endif
#ifndef LOGLEVEL_INFO
#  define LOGLEVEL_INFO 6
#endif
#ifndef LOGLEVEL_DEBUG
#  define LOGLEVEL_DEBUG 7
#endif

const char *syslog_levels[] = {
	XLAT_INDEXED(LOGLEVEL_EMERG),
	XLAT_INDEXED(LOGLEVEL_ALERT),
	XLAT_INDEXED(LOGLEVEL_CRIT),
	XLAT_INDEXED(LOGLEVEL_ERR),
	XLAT_INDEXED(LOGLEVEL_WARNING),
	XLAT_INDEXED(LOGLEVEL_NOTICE),
	XLAT_INDEXED(LOGLEVEL_INFO),
	XLAT_INDEXED(LOGLEVEL_DEBUG),
};

#endif