#ifndef PROCESS_XLAT_H
#define PROCESS_XLAT_H

#include "xlat.h"
#include <asm/prctl.h>

const t_xlat_data arch_prctl_operations_data[] = {
	XLAT(ARCH_XCOMP_TILECFG),
	XLAT(ARCH_XCOMP_TILEDATA),
	XLAT(ARCH_SET_GS),
	XLAT(ARCH_SET_FS),
	XLAT(ARCH_GET_FS),
	XLAT(ARCH_GET_GS),
	XLAT(ARCH_GET_CPUID),
	XLAT(ARCH_SET_CPUID),
	XLAT(ARCH_GET_XCOMP_SUPP),
	XLAT(ARCH_GET_XCOMP_PERM),
	XLAT(ARCH_REQ_XCOMP_PERM),
	XLAT(ARCH_GET_XCOMP_GUEST_PERM),
	XLAT(ARCH_REQ_XCOMP_GUEST_PERM),
	XLAT(ARCH_MAP_VDSO_X32),
	XLAT(ARCH_MAP_VDSO_32),
	XLAT(ARCH_MAP_VDSO_64),
	XLAT(ARCH_GET_UNTAG_MASK),
	XLAT(ARCH_ENABLE_TAGGED_ADDR),
	XLAT(ARCH_GET_MAX_TAG_BITS),
	XLAT(ARCH_FORCE_TAGGED_SVA),
	XLAT(ARCH_SHSTK_ENABLE),
	XLAT(ARCH_SHSTK_DISABLE),
	XLAT(ARCH_SHSTK_LOCK),
	XLAT(ARCH_SHSTK_UNLOCK),
	XLAT(ARCH_SHSTK_STATUS),
};
WSXLAT(arch_prctl_operations);

#endif /* PROCESS_XLAT_H */