#ifndef SECCOMP_XLAT_H
#define SECCOMP_XLAT_H

#include "xlat.h"

#include <linux/seccomp.h>

const char *seccomp_operations[] = {
	XLAT_INDEXED(SECCOMP_SET_MODE_STRICT),
	XLAT_INDEXED(SECCOMP_SET_MODE_FILTER),
	XLAT_INDEXED(SECCOMP_GET_ACTION_AVAIL),
	XLAT_INDEXED(SECCOMP_GET_NOTIF_SIZES)
};

const t_xlat_data seccomp_filter_flags_data[] = {
	XLAT(SECCOMP_FILTER_FLAG_TSYNC),
	XLAT(SECCOMP_FILTER_FLAG_LOG),
	XLAT(SECCOMP_FILTER_FLAG_SPEC_ALLOW),
	XLAT(SECCOMP_FILTER_FLAG_NEW_LISTENER),
	XLAT(SECCOMP_FILTER_FLAG_TSYNC_ESRCH),
	XLAT(SECCOMP_FILTER_FLAG_WAIT_KILLABLE_RECV),
};
WXLAT(seccomp_filter_flags);

#endif /* SECCOMP_XLAT_H */