#ifndef SIGNAL_XLAT_H
#define SIGNAL_XLAT_H

#ifndef __USE_POSIX
#  define __USE_POSIX
#endif
#define _GNU_SOURCE
#include "xlat.h"
#include <asm-generic/signal-defs.h>

#include <signal.h>

const char *signal_names[] = {
	XLAT_INDEXED(SIGHUP),
	XLAT_INDEXED(SIGINT),
	XLAT_INDEXED(SIGQUIT),
	XLAT_INDEXED(SIGILL),
	XLAT_INDEXED(SIGTRAP),
	// XLAT_INDEXED(SIGABRT),
	XLAT_INDEXED(SIGIOT),
	XLAT_INDEXED(SIGBUS),
	XLAT_INDEXED(SIGFPE),
	XLAT_INDEXED(SIGKILL),
	XLAT_INDEXED(SIGUSR1),
	XLAT_INDEXED(SIGSEGV),
	XLAT_INDEXED(SIGUSR2),
	XLAT_INDEXED(SIGPIPE),
	XLAT_INDEXED(SIGALRM),
	XLAT_INDEXED(SIGTERM),
	XLAT_INDEXED(SIGSTKFLT),
	XLAT_INDEXED(SIGCHLD),
	XLAT_INDEXED(SIGCONT),
	XLAT_INDEXED(SIGSTOP),
	XLAT_INDEXED(SIGTSTP),
	XLAT_INDEXED(SIGTTIN),
	XLAT_INDEXED(SIGTTOU),
	XLAT_INDEXED(SIGURG),
	XLAT_INDEXED(SIGXCPU),
	XLAT_INDEXED(SIGXFSZ),
	XLAT_INDEXED(SIGVTALRM),
	XLAT_INDEXED(SIGPROF),
	XLAT_INDEXED(SIGWINCH),
	XLAT_INDEXED(SIGIO),
	// XLAT_INDEXED(SIGPOLL),
	XLAT_INDEXED(SIGPWR),
	XLAT_INDEXED(SIGSYS),
};

const t_xlat_data sigaction_sa_flags_data[] = {
	XLAT(SA_NOCLDSTOP),
	XLAT(SA_NOCLDWAIT),
	XLAT(SA_SIGINFO),
	XLAT(SA_UNSUPPORTED),
	XLAT(SA_EXPOSE_TAGBITS),
	XLAT(SA_ONSTACK),
	XLAT(SA_RESTART),
	XLAT(SA_NODEFER),
	XLAT(SA_RESETHAND),
	XLAT(SA_NOMASK),
	XLAT(SA_ONESHOT),
};
WXLAT(sigaction_sa_flags);

const t_xlat_data sa_handlers_data[] = {
	XLAT_TYPED(unsigned long, SIG_ERR),
	XLAT_TYPED(unsigned long, SIG_DFL),
	XLAT_TYPED(unsigned long, SIG_IGN),
};
WXLAT(sa_handlers);

#endif