#ifndef SIGNAL_XLAT_H
#define SIGNAL_XLAT_H

#ifndef __USE_POSIX
#  define __USE_POSIX
#endif
#define _GNU_SOURCE
#include "xlat.h"
#include <asm-generic/signal-defs.h>

#include <signal.h>

#ifndef SA_RESTORER
#  define SA_RESTORER 0x04000000
#endif

const char *signal_names[] = {
	XLAT_INDEXED(SIGHUP),
	XLAT_INDEXED(SIGINT),
	XLAT_INDEXED(SIGQUIT),
	XLAT_INDEXED(SIGILL),
	XLAT_INDEXED(SIGTRAP),
	XLAT_INDEXED(SIGABRT),
#if defined(SIGIOT) && SIGIOT != SIGABRT
	XLAT_INDEXED(SIGIOT),
#endif
	XLAT_INDEXED(SIGBUS),
	XLAT_INDEXED(SIGFPE),
	XLAT_INDEXED(SIGKILL),
	XLAT_INDEXED(SIGUSR1),
	XLAT_INDEXED(SIGSEGV),
	XLAT_INDEXED(SIGUSR2),
	XLAT_INDEXED(SIGPIPE),
	XLAT_INDEXED(SIGALRM),
	XLAT_INDEXED(SIGTERM),
	XLAT_INDEXED(SIGSTKFLT),
	XLAT_INDEXED(SIGCHLD),
	XLAT_INDEXED(SIGCONT),
	XLAT_INDEXED(SIGSTOP),
	XLAT_INDEXED(SIGTSTP),
	XLAT_INDEXED(SIGTTIN),
	XLAT_INDEXED(SIGTTOU),
	XLAT_INDEXED(SIGURG),
	XLAT_INDEXED(SIGXCPU),
	XLAT_INDEXED(SIGXFSZ),
	XLAT_INDEXED(SIGVTALRM),
	XLAT_INDEXED(SIGPROF),
	XLAT_INDEXED(SIGWINCH),
	XLAT_INDEXED(SIGPOLL),
#if defined(SIGIO) && SIGIO != SIGPOLL
	XLAT_INDEXED(SIGIO),
#endif
	XLAT_INDEXED(SIGPWR),
	XLAT_INDEXED(SIGSYS),
};

const t_xlat_data sigaction_sa_flags_data[] = {
	XLAT(SA_NOCLDSTOP),
	XLAT(SA_NOCLDWAIT),
	XLAT(SA_SIGINFO),
	XLAT(SA_UNSUPPORTED),
	XLAT(SA_EXPOSE_TAGBITS),
	XLAT(SA_ONSTACK),
	XLAT(SA_RESTART),
	XLAT(SA_NODEFER),
	XLAT(SA_RESETHAND),
#if defined(SA_NOMASK) && SA_NOMASK != SA_NODEFER
	XLAT(SA_NOMASK),
#endif
#if defined(SA_RESETHAND) && SA_RESETHAND != SA_ONESHOT
	XLAT(SA_ONESHOT),
#endif
	XLAT(SA_RESTORER),
};
WXLAT(sigaction_sa_flags);

const t_xlat_data sa_handlers_data[] = {
	XLAT_TYPED(unsigned long, SIG_ERR),
	XLAT_TYPED(unsigned long, SIG_DFL),
	XLAT_TYPED(unsigned long, SIG_IGN),
};
WXLAT(sa_handlers);

const t_xlat_data sigproc_how_data[] = {
	XLAT(SIG_BLOCK),
	XLAT(SIG_UNBLOCK),
	XLAT(SIG_SETMASK),
};
WXLAT(sigproc_how);

#endif