#ifndef SOCKET_XLAT_H
#define SOCKET_XLAT_H

#include "xlat.h"
#include <sys/socket.h>

#define SOCK_MAX 0xf

const t_xlat_data protocol_families_data[] = {
	XLAT(PF_UNSPEC),
	XLAT(PF_LOCAL),
	XLAT(PF_UNIX),
	XLAT(PF_FILE),
	XLAT(PF_INET),
	XLAT(PF_AX25),
	XLAT(PF_IPX),
	XLAT(PF_APPLETALK),
	XLAT(PF_NETROM),
	XLAT(PF_BRIDGE),
	XLAT(PF_ATMPVC),
	XLAT(PF_X25),
	XLAT(PF_INET6),
	XLAT(PF_ROSE),
	XLAT(PF_DECnet),
	XLAT(PF_NETBEUI),
	XLAT(PF_SECURITY),
	XLAT(PF_KEY),
	XLAT(PF_NETLINK),
	XLAT(PF_ROUTE),
	XLAT(PF_PACKET),
	XLAT(PF_ASH),
	XLAT(PF_ECONET),
	XLAT(PF_ATMSVC),
	XLAT(PF_RDS),
	XLAT(PF_SNA),
	XLAT(PF_IRDA),
	XLAT(PF_PPPOX),
	XLAT(PF_WANPIPE),
	XLAT(PF_LLC),
	XLAT(PF_IB),
	XLAT(PF_MPLS),
	XLAT(PF_CAN),
	XLAT(PF_TIPC),
	XLAT(PF_BLUETOOTH),
	XLAT(PF_IUCV),
	XLAT(PF_RXRPC),
	XLAT(PF_ISDN),
	XLAT(PF_PHONET),
	XLAT(PF_IEEE802154),
	XLAT(PF_CAIF),
	XLAT(PF_ALG),
	XLAT(PF_NFC),
	XLAT(PF_VSOCK),
	XLAT(PF_KCM),
	XLAT(PF_QIPCRTR),
	XLAT(PF_SMC),
	XLAT(PF_XDP),
	XLAT(PF_MCTP),
	XLAT(PF_MAX),
};
WXLAT(protocol_families);

const t_xlat_data address_families_data[] = {
	XLAT(AF_UNSPEC),
	XLAT(AF_LOCAL),
	XLAT(AF_UNIX),
	XLAT(AF_FILE),
	XLAT(AF_INET),
	XLAT(AF_AX25),
	XLAT(AF_IPX),
	XLAT(AF_APPLETALK),
	XLAT(AF_NETROM),
	XLAT(AF_BRIDGE),
	XLAT(AF_ATMPVC),
	XLAT(AF_X25),
	XLAT(AF_INET6),
	XLAT(AF_ROSE),
	XLAT(AF_DECnet),
	XLAT(AF_NETBEUI),
	XLAT(AF_SECURITY),
	XLAT(AF_KEY),
	XLAT(AF_NETLINK),
	XLAT(AF_ROUTE),
	XLAT(AF_PACKET),
	XLAT(AF_ASH),
	XLAT(AF_ECONET),
	XLAT(AF_ATMSVC),
	XLAT(AF_RDS),
	XLAT(AF_SNA),
	XLAT(AF_IRDA),
	XLAT(AF_PPPOX),
	XLAT(AF_WANPIPE),
	XLAT(AF_LLC),
	XLAT(AF_IB),
	XLAT(AF_MPLS),
	XLAT(AF_CAN),
	XLAT(AF_TIPC),
	XLAT(AF_BLUETOOTH),
	XLAT(AF_IUCV),
	XLAT(AF_RXRPC),
	XLAT(AF_ISDN),
	XLAT(AF_PHONET),
	XLAT(AF_IEEE802154),
	XLAT(AF_CAIF),
	XLAT(AF_ALG),
	XLAT(AF_NFC),
	XLAT(AF_VSOCK),
	XLAT(AF_KCM),
	XLAT(AF_QIPCRTR),
	XLAT(AF_SMC),
	XLAT(AF_XDP),
	XLAT(AF_MCTP),
	XLAT(AF_MAX),
};
WXLAT(address_families);

const t_xlat_data socket_types_data[] = {
	XLAT(SOCK_STREAM),
	XLAT(SOCK_DGRAM),
	XLAT(SOCK_RAW),
	XLAT(SOCK_RDM),
	XLAT(SOCK_SEQPACKET),
	XLAT(SOCK_DCCP),
	XLAT(SOCK_PACKET),
};
WXLAT(socket_types);

const t_xlat_data socket_type_flags_data[] = {
	XLAT(SOCK_NONBLOCK),
	XLAT(SOCK_CLOEXEC),
};
WXLAT(socket_type_flags);

const char *af_proto_names[] = {
	"IPPROTO_???",
	"AX25_P_???",
	"NETLINK_???",
	"ETH_P_???",
	"IRDAPROTO_???",
	"CAN_???",
	"BTPROTO_???",
	"AF_???",
	"ISDN_P_???",
	"PN_PROTO_???",
	"CAIFPROTO_???",
	"NFC_SOCKPROTO_???",
	"KCMPROTO_???",
	"SMCPROTO_???",
};

const t_xlat_data msg_flags_data[] = {
	XLAT(MSG_OOB),
	XLAT(MSG_PEEK),
	XLAT(MSG_DONTROUTE),
	XLAT(MSG_CTRUNC),
	XLAT(MSG_PROXY),
	XLAT(MSG_TRUNC),
	XLAT(MSG_DONTWAIT),
	XLAT(MSG_EOR),
	XLAT(MSG_WAITALL),
	XLAT(MSG_FIN),
	XLAT(MSG_SYN),
	XLAT(MSG_CONFIRM),
	XLAT(MSG_RST),
	XLAT(MSG_ERRQUEUE),
	XLAT(MSG_NOSIGNAL),
	XLAT(MSG_MORE),
	XLAT(MSG_WAITFORONE),
	XLAT(MSG_BATCH),
	XLAT(MSG_SOCK_DEVMEM),
	XLAT(MSG_ZEROCOPY),
	XLAT(MSG_FASTOPEN),
	XLAT(MSG_CMSG_CLOEXEC),
};
WXLAT(msg_flags);

const t_xlat_data shutdown_how_data[] = {
	XLAT(SHUT_RD),
	XLAT(SHUT_WR),
	XLAT(SHUT_RDWR),
};
WXLAT(shutdown_how);

#ifndef __USE_MISC
#  define __USE_MISC
#endif
#include <asm-generic/socket.h>
#include <linux/can/raw.h>
#include <netatalk/at.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <netinet/udp.h>
#include <netipx/ipx.h>
#include <netrom/netrom.h>
#include <netrose/rose.h>

const t_xlat_data socket_option_levels_data[] = {
	XLAT(SOL_AAL),
	XLAT(SOL_ALG),
	XLAT(SOL_ATALK),
	XLAT(SOL_ATM),
	XLAT(SOL_AX25),
	XLAT(SOL_BLUETOOTH),
	XLAT(SOL_CAIF),
	XLAT(SOL_CAN_BASE),
	XLAT(SOL_CAN_RAW),
	XLAT(SOL_DCCP),
	XLAT(SOL_DECNET),
	XLAT(SOL_ICMPV6),
	XLAT(SOL_IP),
	XLAT(SOL_IPV6),
	XLAT(SOL_IPX),
	XLAT(SOL_IRDA),
	XLAT(SOL_IUCV),
	XLAT(SOL_KCM),
	XLAT(SOL_LLC),
	XLAT(SOL_MCTP),
	XLAT(SOL_MPTCP),
	XLAT(SOL_NETBEUI),
	XLAT(SOL_NETLINK),
	XLAT(SOL_NETROM),
	XLAT(SOL_NFC),
	XLAT(SOL_PACKET),
	XLAT(SOL_PNPIPE),
	XLAT(SOL_PPPOL2TP),
	XLAT(SOL_RAW),
	XLAT(SOL_RDS),
	XLAT(SOL_ROSE),
	XLAT(SOL_RXRPC),
#ifdef SOL_SCTP
	XLAT(SOL_SCTP),
#endif
	XLAT(SOL_SMC),
	XLAT(SOL_SOCKET),
	XLAT(SOL_TCP),
	XLAT(SOL_TIPC),
	XLAT(SOL_TLS),
	XLAT(SOL_UDP),
#ifdef SOL_UDPLITE
	XLAT(SOL_UDPLITE),
#endif
	XLAT(SOL_VSOCK),
	XLAT(SOL_X25),
	XLAT(SOL_XDP),
};
WXLAT(socket_option_levels);

#ifndef SYS_SOCKET
#  define SYS_SOCKET 1
#endif
#ifndef SYS_BIND
#  define SYS_BIND 2
#endif
#ifndef SYS_CONNECT
#  define SYS_CONNECT 3
#endif
#ifndef SYS_LISTEN
#  define SYS_LISTEN 4
#endif
#ifndef SYS_ACCEPT
#  define SYS_ACCEPT 5
#endif
#ifndef SYS_GETSOCKNAME
#  define SYS_GETSOCKNAME 6
#endif
#ifndef SYS_GETPEERNAME
#  define SYS_GETPEERNAME 7
#endif
#ifndef SYS_SOCKETPAIR
#  define SYS_SOCKETPAIR 8
#endif
#ifndef SYS_SEND
#  define SYS_SEND 9
#endif
#ifndef SYS_RECV
#  define SYS_RECV 10
#endif
#ifndef SYS_SENDTO
#  define SYS_SENDTO 11
#endif
#ifndef SYS_RECVFROM
#  define SYS_RECVFROM 12
#endif
#ifndef SYS_SHUTDOWN
#  define SYS_SHUTDOWN 13
#endif
#ifndef SYS_SETSOCKOPT
#  define SYS_SETSOCKOPT 14
#endif
#ifndef SYS_GETSOCKOPT
#  define SYS_GETSOCKOPT 15
#endif
#ifndef SYS_SENDMSG
#  define SYS_SENDMSG 16
#endif
#ifndef SYS_RECVMSG
#  define SYS_RECVMSG 17
#endif
#ifndef SYS_ACCEPT4
#  define SYS_ACCEPT4 18
#endif
#ifndef SYS_RECVMMSG
#  define SYS_RECVMMSG 19
#endif
#ifndef SYS_SENDMMSG
#  define SYS_SENDMMSG 20
#endif

const t_xlat_data socketcalls_data[] = {
	XLAT(SYS_SOCKET),
	XLAT(SYS_BIND),
	XLAT(SYS_CONNECT),
	XLAT(SYS_LISTEN),
	XLAT(SYS_ACCEPT),
	XLAT(SYS_GETSOCKNAME),
	XLAT(SYS_GETPEERNAME),
	XLAT(SYS_SOCKETPAIR),
	XLAT(SYS_SEND),
	XLAT(SYS_RECV),
	XLAT(SYS_SENDTO),
	XLAT(SYS_RECVFROM),
	XLAT(SYS_SHUTDOWN),
	XLAT(SYS_SETSOCKOPT),
	XLAT(SYS_GETSOCKOPT),
	XLAT(SYS_SENDMSG),
	XLAT(SYS_RECVMSG),
	XLAT(SYS_ACCEPT4),
	XLAT(SYS_RECVMMSG),
	XLAT(SYS_SENDMMSG),
};
WXLAT(socketcalls);

#endif