#ifndef STATFS_XLAT_H
#define STATFS_XLAT_H

#include "fsmagic.h"
#include "xlat.h"

#include <sys/statvfs.h>

const t_xlat_data filesystem_types_data[] = {
	XLAT(QNX4_SUPER_MAGIC),
	XLAT(AUTOFS_SUPER_MAGIC),
	XLAT(DEVFS_SUPER_MAGIC),
	XLAT(EXT_SUPER_MAGIC),
	XLAT(MINIX_SUPER_MAGIC),
	XLAT(MINIX_SUPER_MAGIC2),
	XLAT(DEVPTS_SUPER_MAGIC),
	XLAT(MINIX2_SUPER_MAGIC),
	XLAT(MINIX2_SUPER_MAGIC2),
	XLAT(NILFS_SUPER_MAGIC),
	XLAT(HFS_SUPER_MAGIC),
	XLAT(MSDOS_SUPER_MAGIC),
	XLAT(MINIX3_SUPER_MAGIC),
	XLAT(SMB_SUPER_MAGIC),
	XLAT(NCP_SUPER_MAGIC),
	XLAT(NFS_SUPER_MAGIC),
	XLAT(ROMFS_MAGIC),
	XLAT(JFFS2_SUPER_MAGIC),
	XLAT(ISOFS_SUPER_MAGIC),
	XLAT(PROC_SUPER_MAGIC),
	XLAT(OPENPROM_SUPER_MAGIC),
	XLAT(USBDEVICE_SUPER_MAGIC),
	XLAT(DFS_SUPER_MAGIC),
	XLAT(AFFS_SUPER_MAGIC),
	XLAT(EXT2_OLD_SUPER_MAGIC),
	XLAT(EXT2_SUPER_MAGIC),
	XLAT(EXT3_SUPER_MAGIC),
	XLAT(EXT4_SUPER_MAGIC),
	XLAT(ECRYPTFS_SUPER_MAGIC),
	XLAT(UFS_MAGIC),
	XLAT(CGROUP_SUPER_MAGIC),
	XLAT(EFS_SUPER_MAGIC),
	XLAT(HOSTFS_SUPER_MAGIC),
	XLAT(TMPFS_MAGIC),
	XLAT(V9FS_MAGIC),
	XLAT(_XIAFS_SUPER_MAGIC),
	XLAT(XENIX_SUPER_MAGIC),
	XLAT(SYSV4_SUPER_MAGIC),
	XLAT(SYSV2_SUPER_MAGIC),
	XLAT(COH_SUPER_MAGIC),
	XLAT(ANON_INODE_FS_MAGIC),
	XLAT(FUTEXFS_SUPER_MAGIC),
	XLAT(MTD_INODE_FS_MAGIC),
	XLAT(UDF_SUPER_MAGIC),
	XLAT(MQUEUE_MAGIC),
	XLAT(BFS_MAGIC),
	XLAT(CRAMFS_MAGIC),
	XLAT(JFS_SUPER_MAGIC),
	XLAT(BEFS_SUPER_MAGIC),
	XLAT(BINFMTFS_MAGIC),
	XLAT(SMACK_MAGIC),
	XLAT(PIPEFS_MAGIC),
	XLAT(REISERFS_SUPER_MAGIC),
	XLAT(AFS_SUPER_MAGIC),
	XLAT(NTFS_SB_MAGIC),
	XLAT(SOCKFS_MAGIC),
	XLAT(XFS_SUPER_MAGIC),
	XLAT(PSTOREFS_MAGIC),
	XLAT(BDEVFS_MAGIC),
	XLAT(SYSFS_MAGIC),
	XLAT(CGROUP2_SUPER_MAGIC),
	XLAT(DEBUGFS_MAGIC),
	XLAT(FUSE_SUPER_MAGIC),
	XLAT(QNX6_SUPER_MAGIC),
	XLAT(NSFS_MAGIC),
	XLAT(SECURITYFS_MAGIC),
	XLAT(SQUASHFS_MAGIC),
	XLAT(BTRFS_TEST_MAGIC),
	XLAT(CODA_SUPER_MAGIC),
	XLAT(OCFS2_SUPER_MAGIC),
	XLAT(TRACEFS_MAGIC),
	XLAT(OVERLAYFS_SUPER_MAGIC),
	XLAT(RAMFS_MAGIC),
	XLAT(BTRFS_SUPER_MAGIC),
	XLAT(HUGETLBFS_MAGIC),
	XLAT(VXFS_SUPER_MAGIC),
	XLAT(XENFS_SUPER_MAGIC),
	XLAT(BPF_FS_MAGIC),
	XLAT(EFIVARFS_MAGIC),
	XLAT(F2FS_SUPER_MAGIC),
	XLAT(SELINUX_MAGIC),
	XLAT(HPFS_SUPER_MAGIC),
	XLAT(SMB2_MAGIC_NUMBER),
	XLAT(CIFS_MAGIC_NUMBER),
};
WXLAT(filesystem_types);

#ifndef ST_RDONLY
#  define ST_RDONLY 0x1
#endif
#ifndef ST_NOSUID
#  define ST_NOSUID 0x2
#endif
#ifndef ST_NODEV
#  define ST_NODEV 0x4
#endif
#ifndef ST_NOEXEC
#  define ST_NOEXEC 0x8
#endif
#ifndef ST_SYNCHRONOUS
#  define ST_SYNCHRONOUS 0x10
#endif
#ifndef ST_MANDLOCK
#  define ST_MANDLOCK 0x40
#endif
#ifndef ST_WRITE
#  define ST_WRITE 0x80
#endif
#ifndef ST_APPEND
#  define ST_APPEND 0x100
#endif
#ifndef ST_IMMUTABLE
#  define ST_IMMUTABLE 0x200
#endif
#ifndef ST_NOATIME
#  define ST_NOATIME 0x400
#endif
#ifndef ST_NODIRATIME
#  define ST_NODIRATIME 0x800
#endif
#ifndef ST_RELATIME
#  define ST_RELATIME 0x1000
#endif
#ifndef ST_NOSYMFOLLOW
#  define ST_NOSYMFOLLOW 0x2000
#endif

const t_xlat_data filesystem_flags_data[] = {
	XLAT(ST_RDONLY),
	XLAT(ST_NOSUID),
	XLAT(ST_NODEV),
	XLAT(ST_NOEXEC),
	XLAT(ST_SYNCHRONOUS),
	XLAT(ST_MANDLOCK),
	XLAT(ST_WRITE),
	XLAT(ST_APPEND),
	XLAT(ST_IMMUTABLE),
	XLAT(ST_NOATIME),
	XLAT(ST_NODIRATIME),
	XLAT(ST_RELATIME),
	XLAT(ST_NOSYMFOLLOW),
};
WXLAT(filesystem_flags);

#endif /* STATFS_XLAT_H */