#ifndef SYS_XLAT_H
#define SYS_XLAT_H

#include "xlat.h"

#include <sys/prctl.h>
#include <sys/resource.h>

const char *rlimit_resources[] = {
	XLAT_INDEXED(RLIMIT_CPU),
	XLAT_INDEXED(RLIMIT_FSIZE),
	XLAT_INDEXED(RLIMIT_DATA),
	XLAT_INDEXED(RLIMIT_STACK),
	XLAT_INDEXED(RLIMIT_CORE),
	XLAT_INDEXED(RLIMIT_RSS),
	XLAT_INDEXED(RLIMIT_NOFILE),
	XLAT_INDEXED(RLIMIT_AS),
	XLAT_INDEXED(RLIMIT_NPROC),
	XLAT_INDEXED(RLIMIT_MEMLOCK),
	XLAT_INDEXED(RLIMIT_LOCKS),
	XLAT_INDEXED(RLIMIT_SIGPENDING),
	XLAT_INDEXED(RLIMIT_MSGQUEUE),
	XLAT_INDEXED(RLIMIT_NICE),
	XLAT_INDEXED(RLIMIT_RTPRIO),
	XLAT_INDEXED(RLIMIT_RTTIME),
	XLAT_INDEXED(RLIMIT_NLIMITS),
};

const t_xlat_data rusage_who_data[] = {
	XLAT(RUSAGE_CHILDREN),
	XLAT(RUSAGE_SELF),
};
WXLAT(rusage_who);

const char *priorities[] = {
	XLAT_INDEXED(PRIO_PROCESS),
	XLAT_INDEXED(PRIO_PGRP),
	XLAT_INDEXED(PRIO_USER),
};

#ifndef PR_SET_PDEATHSIG
#  define PR_SET_PDEATHSIG 1
#endif
#ifndef PR_GET_PDEATHSIG
#  define PR_GET_PDEATHSIG 2
#endif
#ifndef PR_GET_DUMPABLE
#  define PR_GET_DUMPABLE 3
#endif
#ifndef PR_SET_DUMPABLE
#  define PR_SET_DUMPABLE 4
#endif
#ifndef PR_GET_UNALIGN
#  define PR_GET_UNALIGN 5
#endif
#ifndef PR_SET_UNALIGN
#  define PR_SET_UNALIGN 6
#endif
#ifndef PR_GET_KEEPCAPS
#  define PR_GET_KEEPCAPS 7
#endif
#ifndef PR_SET_KEEPCAPS
#  define PR_SET_KEEPCAPS 8
#endif
#ifndef PR_GET_FPEMU
#  define PR_GET_FPEMU 9
#endif
#ifndef PR_SET_FPEMU
#  define PR_SET_FPEMU 10
#endif
#ifndef PR_GET_FPEXC
#  define PR_GET_FPEXC 11
#endif
#ifndef PR_SET_FPEXC
#  define PR_SET_FPEXC 12
#endif
#ifndef PR_GET_TIMING
#  define PR_GET_TIMING 13
#endif
#ifndef PR_SET_TIMING
#  define PR_SET_TIMING 14
#endif
#ifndef PR_SET_NAME
#  define PR_SET_NAME 15
#endif
#ifndef PR_GET_NAME
#  define PR_GET_NAME 16
#endif
#ifndef PR_GET_ENDIAN
#  define PR_GET_ENDIAN 19
#endif
#ifndef PR_SET_ENDIAN
#  define PR_SET_ENDIAN 20
#endif
#ifndef PR_GET_SECCOMP
#  define PR_GET_SECCOMP 21
#endif
#ifndef PR_SET_SECCOMP
#  define PR_SET_SECCOMP 22
#endif
#ifndef PR_CAPBSET_READ
#  define PR_CAPBSET_READ 23
#endif
#ifndef PR_CAPBSET_DROP
#  define PR_CAPBSET_DROP 24
#endif
#ifndef PR_GET_TSC
#  define PR_GET_TSC 25
#endif
#ifndef PR_SET_TSC
#  define PR_SET_TSC 26
#endif
#ifndef PR_GET_SECUREBITS
#  define PR_GET_SECUREBITS 27
#endif
#ifndef PR_SET_SECUREBITS
#  define PR_SET_SECUREBITS 28
#endif
#ifndef PR_SET_TIMERSLACK
#  define PR_SET_TIMERSLACK 29
#endif
#ifndef PR_GET_TIMERSLACK
#  define PR_GET_TIMERSLACK 30
#endif
#ifndef PR_TASK_PERF_EVENTS_DISABLE
#  define PR_TASK_PERF_EVENTS_DISABLE 31
#endif
#ifndef PR_TASK_PERF_EVENTS_ENABLE
#  define PR_TASK_PERF_EVENTS_ENABLE 32
#endif
#ifndef PR_MCE_KILL
#  define PR_MCE_KILL 33
#endif
#ifndef PR_MCE_KILL_GET
#  define PR_MCE_KILL_GET 34
#endif
#ifndef PR_SET_MM
#  define PR_SET_MM 35
#endif
#ifndef PR_SET_CHILD_SUBREAPER
#  define PR_SET_CHILD_SUBREAPER 36
#endif
#ifndef PR_GET_CHILD_SUBREAPER
#  define PR_GET_CHILD_SUBREAPER 37
#endif
#ifndef PR_SET_NO_NEW_PRIVS
#  define PR_SET_NO_NEW_PRIVS 38
#endif
#ifndef PR_GET_NO_NEW_PRIVS
#  define PR_GET_NO_NEW_PRIVS 39
#endif
#ifndef PR_GET_TID_ADDRESS
#  define PR_GET_TID_ADDRESS 40
#endif
#ifndef PR_SET_THP_DISABLE
#  define PR_SET_THP_DISABLE 41
#endif
#ifndef PR_GET_THP_DISABLE
#  define PR_GET_THP_DISABLE 42
#endif
#ifndef PR_MPX_ENABLE_MANAGEMENT
#  define PR_MPX_ENABLE_MANAGEMENT 43
#endif
#ifndef PR_MPX_DISABLE_MANAGEMENT
#  define PR_MPX_DISABLE_MANAGEMENT 44
#endif
#ifndef PR_SET_FP_MODE
#  define PR_SET_FP_MODE 45
#endif
#ifndef PR_GET_FP_MODE
#  define PR_GET_FP_MODE 46
#endif
#ifndef PR_CAP_AMBIENT
#  define PR_CAP_AMBIENT 47
#endif
#ifndef PR_SVE_SET_VL
#  define PR_SVE_SET_VL 50
#endif
#ifndef PR_SVE_GET_VL
#  define PR_SVE_GET_VL 51
#endif
#ifndef PR_GET_SPECULATION_CTRL
#  define PR_GET_SPECULATION_CTRL 52
#endif
#ifndef PR_SET_SPECULATION_CTRL
#  define PR_SET_SPECULATION_CTRL 53
#endif
#ifndef PR_PAC_RESET_KEYS
#  define PR_PAC_RESET_KEYS 54
#endif
#ifndef PR_SET_TAGGED_ADDR_CTRL
#  define PR_SET_TAGGED_ADDR_CTRL 55
#endif
#ifndef PR_GET_TAGGED_ADDR_CTRL
#  define PR_GET_TAGGED_ADDR_CTRL 56
#endif
#ifndef PR_SET_IO_FLUSHER
#  define PR_SET_IO_FLUSHER 57
#endif
#ifndef PR_GET_IO_FLUSHER
#  define PR_GET_IO_FLUSHER 58
#endif
#ifndef PR_SET_SYSCALL_USER_DISPATCH
#  define PR_SET_SYSCALL_USER_DISPATCH 59
#endif
#ifndef PR_PAC_SET_ENABLED_KEYS
#  define PR_PAC_SET_ENABLED_KEYS 60
#endif
#ifndef PR_PAC_GET_ENABLED_KEYS
#  define PR_PAC_GET_ENABLED_KEYS 61
#endif
#ifndef PR_SCHED_CORE
#  define PR_SCHED_CORE 62
#endif
#ifndef PR_SME_SET_VL
#  define PR_SME_SET_VL 63
#endif
#ifndef PR_SME_GET_VL
#  define PR_SME_GET_VL 64
#endif
#ifndef PR_SET_MDWE
#  define PR_SET_MDWE 65
#endif
#ifndef PR_GET_MDWE
#  define PR_GET_MDWE 66
#endif
#ifndef PR_SET_MEMORY_MERGE
#  define PR_SET_MEMORY_MERGE 67
#endif
#ifndef PR_GET_MEMORY_MERGE
#  define PR_GET_MEMORY_MERGE 68
#endif
#ifndef PR_RISCV_V_SET_CONTROL
#  define PR_RISCV_V_SET_CONTROL 69
#endif
#ifndef PR_RISCV_V_GET_CONTROL
#  define PR_RISCV_V_GET_CONTROL 70
#endif
#ifndef PR_RISCV_SET_ICACHE_FLUSH_CTX
#  define PR_RISCV_SET_ICACHE_FLUSH_CTX 71
#endif
#ifndef PR_PPC_GET_DEXCR
#  define PR_PPC_GET_DEXCR 72
#endif
#ifndef PR_PPC_SET_DEXCR
#  define PR_PPC_SET_DEXCR 73
#endif
#ifndef PR_GET_SHADOW_STACK_STATUS
#  define PR_GET_SHADOW_STACK_STATUS 74
#endif
#ifndef PR_SET_SHADOW_STACK_STATUS
#  define PR_SET_SHADOW_STACK_STATUS 75
#endif
#ifndef PR_LOCK_SHADOW_STACK_STATUS
#  define PR_LOCK_SHADOW_STACK_STATUS 76
#endif
#ifndef PR_TIMER_CREATE_RESTORE_IDS
#  define PR_TIMER_CREATE_RESTORE_IDS 77
#endif
#ifndef PR_FUTEX_HASH
#  define PR_FUTEX_HASH 78
#endif
#ifndef PR_GET_AUXV
#  define PR_GET_AUXV 0x41555856
#endif
#ifndef PR_SET_VMA
#  define PR_SET_VMA 0x53564d41
#endif
#ifndef PR_SET_PTRACER
#  define PR_SET_PTRACER 0x59616d61
#endif

const t_xlat_data prctl_options_data[] = {
	XLAT(PR_SET_PDEATHSIG),
	XLAT(PR_GET_PDEATHSIG),
	XLAT(PR_GET_DUMPABLE),
	XLAT(PR_SET_DUMPABLE),
	XLAT(PR_GET_UNALIGN),
	XLAT(PR_SET_UNALIGN),
	XLAT(PR_GET_KEEPCAPS),
	XLAT(PR_SET_KEEPCAPS),
	XLAT(PR_GET_FPEMU),
	XLAT(PR_SET_FPEMU),
	XLAT(PR_GET_FPEXC),
	XLAT(PR_SET_FPEXC),
	XLAT(PR_GET_TIMING),
	XLAT(PR_SET_TIMING),
	XLAT(PR_SET_NAME),
	XLAT(PR_GET_NAME),
	XLAT(PR_GET_ENDIAN),
	XLAT(PR_SET_ENDIAN),
	XLAT(PR_GET_SECCOMP),
	XLAT(PR_SET_SECCOMP),
	XLAT(PR_CAPBSET_READ),
	XLAT(PR_CAPBSET_DROP),
	XLAT(PR_GET_TSC),
	XLAT(PR_SET_TSC),
	XLAT(PR_GET_SECUREBITS),
	XLAT(PR_SET_SECUREBITS),
	XLAT(PR_SET_TIMERSLACK),
	XLAT(PR_GET_TIMERSLACK),
	XLAT(PR_TASK_PERF_EVENTS_DISABLE),
	XLAT(PR_TASK_PERF_EVENTS_ENABLE),
	XLAT(PR_MCE_KILL),
	XLAT(PR_MCE_KILL_GET),
	XLAT(PR_SET_MM),
	XLAT(PR_SET_CHILD_SUBREAPER),
	XLAT(PR_GET_CHILD_SUBREAPER),
	XLAT(PR_SET_NO_NEW_PRIVS),
	XLAT(PR_GET_NO_NEW_PRIVS),
	XLAT(PR_GET_TID_ADDRESS),
	XLAT(PR_SET_THP_DISABLE),
	XLAT(PR_GET_THP_DISABLE),
	XLAT(PR_MPX_ENABLE_MANAGEMENT),
	XLAT(PR_MPX_DISABLE_MANAGEMENT),
	XLAT(PR_SET_FP_MODE),
	XLAT(PR_GET_FP_MODE),
	XLAT(PR_CAP_AMBIENT),
	XLAT(PR_SVE_SET_VL),
	XLAT(PR_SVE_GET_VL),
	XLAT(PR_GET_SPECULATION_CTRL),
	XLAT(PR_SET_SPECULATION_CTRL),
	XLAT(PR_PAC_RESET_KEYS),
	XLAT(PR_SET_TAGGED_ADDR_CTRL),
	XLAT(PR_GET_TAGGED_ADDR_CTRL),
	XLAT(PR_SET_IO_FLUSHER),
	XLAT(PR_GET_IO_FLUSHER),
	XLAT(PR_SET_SYSCALL_USER_DISPATCH),
	XLAT(PR_PAC_SET_ENABLED_KEYS),
	XLAT(PR_PAC_GET_ENABLED_KEYS),
	XLAT(PR_SCHED_CORE),
	XLAT(PR_SME_SET_VL),
	XLAT(PR_SME_GET_VL),
	XLAT(PR_SET_MDWE),
	XLAT(PR_GET_MDWE),
	XLAT(PR_SET_MEMORY_MERGE),
	XLAT(PR_GET_MEMORY_MERGE),
	XLAT(PR_RISCV_V_SET_CONTROL),
	XLAT(PR_RISCV_V_GET_CONTROL),
	XLAT(PR_RISCV_SET_ICACHE_FLUSH_CTX),
	XLAT(PR_PPC_GET_DEXCR),
	XLAT(PR_PPC_SET_DEXCR),
	XLAT(PR_GET_SHADOW_STACK_STATUS),
	XLAT(PR_SET_SHADOW_STACK_STATUS),
	XLAT(PR_LOCK_SHADOW_STACK_STATUS),
	XLAT(PR_TIMER_CREATE_RESTORE_IDS),
	XLAT(PR_FUTEX_HASH),
	XLAT(PR_GET_AUXV),
	XLAT(PR_SET_VMA),
	XLAT(PR_SET_PTRACER),
};
WSXLAT(prctl_options);

#endif
