#ifndef SYS_XLAT_H
#define SYS_XLAT_H

#include "xlat.h"

#include <sys/resource.h>

const char *rlimit_resources[] = {
	XLAT_INDEXED(RLIMIT_CPU),
	XLAT_INDEXED(RLIMIT_FSIZE),
	XLAT_INDEXED(RLIMIT_DATA),
	XLAT_INDEXED(RLIMIT_STACK),
	XLAT_INDEXED(RLIMIT_CORE),
	XLAT_INDEXED(RLIMIT_RSS),
	XLAT_INDEXED(RLIMIT_NOFILE),
	XLAT_INDEXED(RLIMIT_AS),
	XLAT_INDEXED(RLIMIT_NPROC),
	XLAT_INDEXED(RLIMIT_MEMLOCK),
	XLAT_INDEXED(RLIMIT_LOCKS),
	XLAT_INDEXED(RLIMIT_SIGPENDING),
	XLAT_INDEXED(RLIMIT_MSGQUEUE),
	XLAT_INDEXED(RLIMIT_NICE),
	XLAT_INDEXED(RLIMIT_RTPRIO),
	XLAT_INDEXED(RLIMIT_RTTIME),
	XLAT_INDEXED(RLIMIT_NLIMITS),
};

const t_xlat_data rusage_who_data[] = {
	XLAT(RUSAGE_CHILDREN),
	XLAT(RUSAGE_SELF),
};
WXLAT(rusage_who);

#endif